name: CI Pipeline
on:
  push:
    branches:
      - "[0-9]+.[0-9]+.x"
  pull_request:

jobs:
  static-analysis:
    name: "Static Analysis"
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: true
      matrix:
        php: ["8.0"]
        os: ["ubuntu-latest"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup PHP
        uses: shivammathur/setup-php@2.11.0
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Analyze code with static-analysis
        run: vendor/bin/phpstan analyse --level=max --no-progress src

  unit-tests:
    name: "Unit Tests"
    runs-on: "${{ matrix.os }}"
    continue-on-error: "${{ matrix.experimental }}"
    strategy:
      fail-fast: false
      matrix:
        php: ["8.0", "8.1"]
        os: ["ubuntu-latest"]
        experimental: [false]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup PHP
        uses: shivammathur/setup-php@2.11.0
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader ${{ matrix.composer-options }}

      - name: Execute tests
        run: vendor/bin/phpunit --colors=always --coverage-text
